import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)

GPIO.setup(17, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(23, GPIO.OUT)
GPIO.setup(24, GPIO.OUT)
GPIO.setup(25, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(26, GPIO.OUT)

try:
  GPIO.output(17, GPIO.HIGH)
  time.sleep(1)
  GPIO.output(17, GPIO.LOW)
  time.sleep(1)
  GPIO.output(27, GPIO.HIGH)
  time.sleep(1)
  GPIO.output(27, GPIO.LOW)
  time.sleep(1)
  GPIO.output(22, GPIO.HIGH)
  time.sleep(1)
  GPIO.output(22, GPIO.LOW)
  time.sleep(1)
  GPIO.output(23, GPIO.HIGH)
  time.sleep(1)
  GPIO.output(23, GPIO.LOW)
  time.sleep(1)
  GPIO.output(24, GPIO.HIGH)
  time.sleep(1)
  GPIO.output(24, GPIO.LOW)
  time.sleep(1)
  GPIO.output(25, GPIO.HIGH)
  time.sleep(1)
  GPIO.output(25, GPIO.LOW)
  time.sleep(1)    
  GPIO.output(16, GPIO.HIGH)
  time.sleep(1)
  GPIO.output(16, GPIO.LOW)
  time.sleep(1)
  GPIO.output(26, GPIO.HIGH)
  time.sleep(1)
  GPIO.output(26, GPIO.LOW)
  time.sleep(1)
finally:
  GPIO.cleanup()
